/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { OnchainRiddle } from "./OnchainRiddle";
export * as factories from "./factories";
export { OnchainRiddle__factory } from "./factories/OnchainRiddle__factory";
